### ISSUE TITLE
Where is Semantic Kernel used?

### ISSUE THREAD

**Issue by RafaInformatico** [Azure/aihub#25]
The documentation says that "AI Hub uses Semantic Kernel to orchestrate the prompts, Azure OpenAI calls and Azure Cognitive Search queries and results.", but I cannot find it.
Is it been used, and I have not been able to find it? Is it a plan but the document is ahead of the code? Was it removed and the document is obsolete? Is that in another branch or project?

**Comment by cmendible** [comment]
Documentation is wrong and we will fix it asap.

**Comment by cmendible** [comment]
We just added an OpenAI plugin which uses Semantic Kernel.

**Comment by rliberoff** [comment]
Hi @RafaInformatico,

We apologize for our late response. We have updated the documents related to `Semantic Kernel`.

In the upcoming deployment of the AI Hub, the Semantic Kernel document will include the following information:

>_Currently, the AI Hub does not directly use the Semantic Kernel in its use case examples. However, it does demonstrate its usage through two specific examples that show how easy it is to create OpenAI plugins using Semantic Kernel as an SDK._

>_Here are the available plugin examples:_

> _- Call Analysis: This plugin uses Semantic Kernel to implement features similar to those demonstrated in the Call Center Analytics use case._

>_- Financial Product Comparison: This plugin employs Semantic Kernel to combine native and prompt functions to compare a specific financial product with others in the market. It combines prompts with the Web Search Engine Plugin, which is further integrated with the Bing Search connector._

>_For more information, please refer to the OpenAI Plugins section. You can also learn more about Semantic Kernel in its official documentation._


As you can see, We are also going to introduce a new `OpenAI Plugins` section with additional information about the plugin examples provided by the AI Hub.

In the meantime, we are going to close this issue.

Thank you!
