### ISSUE TITLE
JailBreak detection feature is not working

### ISSUE THREAD

**Issue by heblasco** [Azure/aihub#52]
Double check why JailBreak feature is not working.
After review seems that East US region does not support it.

**Comment by adanbrownpaca** [comment]
It worked for me, but I did have to add the required appsettings.json entry:
"JailbreakDetectionEndpoint": "contentsafety/text:detectJailbreak?api-version=2024-02-15-preview"

This setting comes from the API management website provided after configuring the resource:
![image](https://github.com/Azure/aihub/assets/135455142/4e335b49-235c-41cb-a9b6-1baf9cbfa18f)

Then:
![image](https://github.com/Azure/aihub/assets/135455142/25e3c829-7321-405c-8a70-74abd0b8e5c6)

Then:
![image](https://github.com/Azure/aihub/assets/135455142/f66a615b-2ce5-48df-9173-c7ae9c43be9b)

![image](https://github.com/Azure/aihub/assets/135455142/1b0d3918-50bb-4090-a15a-9a9f820fc596)

It was a bit difficult to find out how to configure it properly, as it is not described in the documentation.

**Comment by rliberoff** [comment]
This issue was due to a temporary error in the platform. It should be solved by now. Closing this issue.

Thank you!
